<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dashboard cards</name>
   <tag></tag>
   <elementGuidId>3397d9e1-01b5-4e62-bd8a-3e68d5d84dea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/div/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bde08435-d6cc-4146-a286-39ea254f6ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-body</value>
      <webElementGuid>e134f8cb-5307-48a1-9c7f-9ef0ca4b4210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Timed meets06</value>
      <webElementGuid>391c7c50-0c27-4e14-82cc-66a49ae4c32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-scroller&quot;]/div[@class=&quot;container-fluid page-body-wrapper&quot;]/div[@class=&quot;main-panel&quot;]/div[@class=&quot;content-wrapper&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 stretch-card grid-margin&quot;]/div[@class=&quot;card card-img-holder&quot;]/div[@class=&quot;card-body&quot;]</value>
      <webElementGuid>a76f4fce-0a30-4487-995a-5d1715e603ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>d94d8660-db45-407a-b8ba-a1f5fdb99601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overall View'])[1]/following::div[4]</value>
      <webElementGuid>76f5759a-551f-4644-8613-9d4e11d1e289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All rights reserved.'])[1]/following::div[8]</value>
      <webElementGuid>e5b40a0f-5d37-40f4-8ed6-fb617497d5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Untimed meets'])[1]/preceding::div[1]</value>
      <webElementGuid>17bcb370-a4ce-43c0-bfc2-08fb9c1adb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div</value>
      <webElementGuid>d3ce8dcd-b1fc-4c1c-b49a-5b5f15ce096c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Timed meets06' or . = 'Timed meets06')]</value>
      <webElementGuid>36a52c1b-bd81-4ec9-80d8-3926acf6f8c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
