<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Facility - New</name>
   <tag></tag>
   <elementGuidId>6c7f7e25-fb2d-4911-aefd-bcb341e04a7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formGridLocation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formGridLocation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59497799-48a7-4b5d-bab6-d88dac7a9425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>location_name</value>
      <webElementGuid>998f3687-3838-4b70-9631-b5c042f56542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Facility Name*</value>
      <webElementGuid>301d496b-0fbe-40f6-a0ee-25a7d20c2604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed674220-1356-475f-9e7b-b2d79b467a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formGridLocation</value>
      <webElementGuid>55c45607-053d-4c26-b7d7-af98923e6778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-auto form-control form-control-lg</value>
      <webElementGuid>f1c332e6-d515-4132-a771-21af155c889f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formGridLocation&quot;)</value>
      <webElementGuid>ba160301-3a9f-410d-b249-ebf36e4d8cbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formGridLocation']</value>
      <webElementGuid>226e926e-2321-44cf-81fb-c934d1c2199b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div/div[3]/div[2]/div/p/div/div/div/form/div/div/div[7]/div/input</value>
      <webElementGuid>98be80fc-bd77-44ce-ae76-2d1986793e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>e1917c99-2be7-4d76-bcbb-a336351d1c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'location_name' and @placeholder = 'Facility Name*' and @type = 'text' and @id = 'formGridLocation']</value>
      <webElementGuid>38413707-7695-4a7b-87da-46c72741ebf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
