<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Facility</name>
   <tag></tag>
   <elementGuidId>0f775c39-e45a-4724-96d0-abada64e2f2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formGridLocation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formGridLocation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41e41ad5-a3e8-4c0c-9af5-2aedffc1f612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>location_name</value>
      <webElementGuid>9064f5bc-a9dc-45d6-8abc-4a1884fde2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Facility Name*</value>
      <webElementGuid>d43e1614-dea2-4efb-bd03-89664d295830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>788f39f0-d52a-4fcb-aeeb-58b58abb3690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formGridLocation</value>
      <webElementGuid>81222eeb-8bfd-47c6-a5f0-8d801708f470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-auto form-control form-control-lg</value>
      <webElementGuid>a703046e-7ed1-4e51-a3c2-b079cdc37019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formGridLocation&quot;)</value>
      <webElementGuid>405c3c70-f464-4d37-81ce-67d33663a437</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formGridLocation']</value>
      <webElementGuid>b1a32396-eb40-4e1e-9988-94f5ce32e3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/form/div/div[2]/div[5]/div/input</value>
      <webElementGuid>d36c1566-6172-483d-acec-3b3796a60d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>5049c45f-408d-40ed-9109-80e8e98054e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'location_name' and @placeholder = 'Facility Name*' and @type = 'text' and @id = 'formGridLocation']</value>
      <webElementGuid>a327ed90-2545-457c-afb3-658182ed5a43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
