<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TC Admin Option - New</name>
   <tag></tag>
   <elementGuidId>cf1b67f0-1bd9-4339-9fa1-57e5ce931ee6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-35-option-25</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-35-option-25']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>014eb00a-84ac-4ff7-9a33-59b60e8cec1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-9gakcf-option</value>
      <webElementGuid>825d7699-56ae-4de0-a57f-02a89c6a9d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>119ada9d-80de-4ee0-a8f4-05e777dabeb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-35-option-25</value>
      <webElementGuid>8e1d1274-0254-4ebf-91c6-e830d10f7551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6a6b0349-aa41-49c2-b8dc-69ee17d93402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kichu Test</value>
      <webElementGuid>1fe7294c-788c-43b8-9dbe-bf45d5686e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-35-option-25&quot;)</value>
      <webElementGuid>25777bd3-0b26-40cb-bb70-eb76d16336cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-35-option-25']</value>
      <webElementGuid>d5e13c14-d6ec-4029-9853-ae107e700d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-35-listbox']/div/div[26]</value>
      <webElementGuid>f9aa4865-5e2b-441a-8bc4-f025c13937a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='vicky QA'])[1]/following::div[1]</value>
      <webElementGuid>b8a46dc9-ba07-488a-af06-5373bfcf7006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NITEESH Vee'])[1]/following::div[2]</value>
      <webElementGuid>d0c76211-81cf-401a-a1c2-206b7c2fc0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NITEESH Vee'])[2]/preceding::div[1]</value>
      <webElementGuid>39acf0ae-af70-42a1-b9a2-ac9e4ab2ca6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NITEESH Vee'])[3]/preceding::div[2]</value>
      <webElementGuid>643cbf78-54f9-4c11-a147-f7f892d49c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]</value>
      <webElementGuid>be4bb7cc-2436-4e8e-864a-a37d243e9e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-35-option-25' and (text() = 'Kichu Test' or . = 'Kichu Test')]</value>
      <webElementGuid>0750038e-e7aa-4c11-bc04-eefa19b676e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
