<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Template Name</name>
   <tag></tag>
   <elementGuidId>b72d15bf-96ce-4e30-9339-efe9f5852ddf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formGridMeetName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formGridMeetName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd9af219-9bcd-4e92-91e9-830ae2464be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>7ae1e472-0841-4236-8680-995150c73915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Template Name*</value>
      <webElementGuid>62d996db-cbef-4374-ad99-8cbcccf9dd2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dda7f7ce-746d-4df1-8251-a835c1dbc9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formGridMeetName</value>
      <webElementGuid>b2592ad5-46d7-43f2-b395-b963c1353ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-auto form-control form-control-lg</value>
      <webElementGuid>bc6bde92-5c2b-4cb1-b17f-34785a5c9995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formGridMeetName&quot;)</value>
      <webElementGuid>14dce0cd-85aa-4bc1-a5e2-602cbf6ecbc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formGridMeetName']</value>
      <webElementGuid>2f8d7f4c-33f0-4a8f-b1c5-8ce06eeae4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div/div[3]/div[2]/div/p/div/div/div/form/div/div/div[2]/div/input</value>
      <webElementGuid>05482d67-c793-40f4-829c-71cf86132ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>282f4c71-a36a-4d86-ae30-2adabf69a2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'name' and @placeholder = 'Template Name*' and @type = 'text' and @id = 'formGridMeetName']</value>
      <webElementGuid>66313851-6151-4489-9fed-88941ec73d97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
