<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Time field</name>
   <tag></tag>
   <elementGuidId>29faf223-377b-47a8-876a-91e9a2df1424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formGridStartTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formGridStartTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f569589-6720-4aa1-ba84-84fe2ee1297a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>meet_time</value>
      <webElementGuid>5938b637-69f4-4a96-9d6b-80f9a10956f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Meet Start Time*</value>
      <webElementGuid>abfd681c-b5ee-4798-bc02-020aae1bbfd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>46683dbe-fdb1-4234-9643-98e2ef632c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formGridStartTime</value>
      <webElementGuid>4a4f83ad-464d-49a1-a2d0-40cd6f82eb8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-auto form-control form-control-lg</value>
      <webElementGuid>854ccc60-cf0f-478e-8544-ccdeba20d4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formGridStartTime&quot;)</value>
      <webElementGuid>f113cf34-599b-43e4-a8d2-df02ab1ef36f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formGridStartTime']</value>
      <webElementGuid>4edd8eba-b523-47f4-8a66-5c889f5559fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/form/div/div[2]/div[8]/div/input</value>
      <webElementGuid>c1d3976a-038c-4efc-a453-8caeda96546d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>47f7665f-76d5-4612-a263-1a1512569236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'meet_time' and @placeholder = 'Meet Start Time*' and @type = 'text' and @id = 'formGridStartTime']</value>
      <webElementGuid>86a66bb6-6d77-4a54-9c89-917f8c53fd95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
