<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Username</name>
   <tag></tag>
   <elementGuidId>e042941a-4c08-4337-a337-c27607800f19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formGridUsername</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formGridUsername']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6246218b-9313-4021-83e5-1748e17ae32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>fb1c9280-65c8-4c0e-9402-bede42973764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email or Mobile Number</value>
      <webElementGuid>9a0c5c4e-cfb6-4b82-a555-2623af47e5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae4e2582-2a2d-4909-8e99-8ca609de5995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formGridUsername</value>
      <webElementGuid>7d615a69-cd7d-43c3-b8e3-8c1e841d7e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-auto form-control form-control-lg</value>
      <webElementGuid>ca30c5f4-f474-42c4-91fa-8a1ef351c318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formGridUsername&quot;)</value>
      <webElementGuid>d093a85f-6716-4290-be16-40d7db2bd935</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formGridUsername']</value>
      <webElementGuid>18b475d9-c621-44fc-99c8-d960a7b3729f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div[2]/div[2]/div/form/div/input</value>
      <webElementGuid>66ee8b30-9036-4c24-aa98-e503c9591619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>55e775f2-b009-42c0-a577-05ad4f8ea41e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username' and @placeholder = 'Email or Mobile Number' and @type = 'text' and @id = 'formGridUsername']</value>
      <webElementGuid>d823ed26-2f45-4348-b550-710900fe99e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
